kind: PersistentVolume
apiVersion: v1
metadata:
  name: jstorm-supervisor-jar-pv
spec:
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: "/opt/jstorm/supervisor/lib"
    server: 192.168.0.132
  persistentVolumeReclaimPolicy: Recycle
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jstorm-supervisor-jar-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
