apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: jstorm-nimbus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: jstorm-nimbus
    spec:
      imagePullSecrets:
          - name: nexus-secret
      containers:
      - name: jstorm-nimbus
        image: 192.168.0.134:9990/jstorm/jstorm-caiex:latest
        imagePullPolicy: Always
        command: ["jstorm","nimbus"]
        volumeMounts:
        - name: logs-v
          mountPath: /opt/jstorm/logs
        - name: logs-trade
          mountPath: /opt/logs/trade
        - name: trade-v
          mountPath: /opt/jstorm/trade
        - name: jar
          mountPath: /opt/jstorm/lib
      volumes:
      - name: logs-v
        hostPath: 
         path: /opt/logs/jstorm
      - name: logs-trade
        hostPath: 
         path: /opt/logs/jstorm/trade
      - name: trade-v
        persistentVolumeClaim:
          claimName: jstorm-trade-pvc
      - name: jar
        persistentVolumeClaim:
          claimName: jstorm-nimbus-jar-pvc

---

apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: jstorm-supervisor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: jstorm-supervisor
    spec:
      imagePullSecrets:
          - name: nexus-secret
      containers:
      - name: jstorm-supervisor
        image: 192.168.0.134:9990/jstorm/jstorm-caiex:latest
        imagePullPolicy: Always
        command: ["jstorm","supervisor"]
        volumeMounts:
        - name: logs-v
          mountPath: /opt/jstorm/logs
        - name: logs-trade
          mountPath: /opt/logs/trade
        - name: trade-v
          mountPath: /opt/jstorm/trade
        - name: jar
          mountPath: /opt/jstorm/lib
      volumes:
      - name: logs-v
        hostPath:
         path: /opt/logs/jstorm
      - name: logs-trade
        hostPath:  
         path: /opt/logs/jstorm/trade
      - name: trade-v
        persistentVolumeClaim:
          claimName: jstorm-trade-pvc
      - name: jar
        persistentVolumeClaim:
          claimName: jstorm-supervisor-jar-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: jstorm-nimbus
spec:
  ports:
    - port: 6627
      targetPort: 6627
  selector:
     app: jstorm-nimbus

---

apiVersion: v1
kind: Service
metadata:
  name: jstorm-supervisor
spec:
  ports:
    - port: 6627
      targetPort: 6627
  selector:
     app: jstorm-supervisor
